services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: appAgentDB
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./disable-name-resolve.cnf:/etc/mysql/conf.d/disable-name-resolve.cnf
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appAgentDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true&connectTimeout=5000&socketTimeout=5000
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    restart: on-failure

volumes:
  db_data:
