spring.application.name=agent_chat

# MongoDB Configuration (Default for local development)
spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.database=appAgentDB

# Logging (Development mode - more verbose)
spring.main.lazy-initialization=true
spring.jmx.enabled=false
logging.level.root=WARN
logging.level.com.agent_chat=DEBUG
logging.level.org.springframework.data.mongodb.core=DEBUG

server.port=2005
